development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://jthlfdvvwgjgar:v9jZNEa1CWWcL5I5OL-c2XkR1o@ec2-54-235-246-220.compute-1.amazonaws.com:5432/d79hriv4bcum7j
